CC=g++
OUTPUT=../../build/
DEPS=../../"chapter7 Classes"/access_specifiers.cpp



exercise17.4:
	$(CC) -o $(OUTPUT)exercise17.4  exercise17.4.cpp  $(DEPS)
	$(OUTPUT)exercise17.4

exercise17.6:
	$(CC) -o $(OUTPUT)exercise17.6  exercise17.6.cpp  $(DEPS)
	$(OUTPUT)exercise17.6